---
kind: List
apiVersion: v1
id: spark-setup
items:
- kind: Service
  apiVersion: v1
  metadata: 
    name: spark-master
    labels: 
      name: spark-master-svc
  spec: 
    ports: 
    - name: service
      port: 7077
      targetPort: 7077
    - name: rest
      port: 6066
      targetPort: 6066
    selector: 
      name: spark-master-pod
- kind: Service
  apiVersion: v1
  metadata: 
    name: spark-master-pub
    labels: 
      name: spark-master-svc-pub
  spec: 
    ports: 
    - name: webui
      port: 8080
      targetPort: 8080
    selector: 
      name: spark-master-pod
- kind: ReplicationController
  apiVersion: v1
  metadata: 
    name: spark-master-rc
    labels: 
      name: spark-master-rc
  spec: 
    replicas: 1
    selector:
      name: spark-master-pod
    template:
      metadata:
        name: spark-master-pod
        labels:
          name: spark-master-pod
      spec:
        containers: 
        - name: spark-master
          image: quay.io/draft/k8s-spark:v0.1
          resources:
            limits:
              cpu: 1
              memory: 4Gi
          env:
          - name: MASTER_ROLE
            value: '1'
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports: 
          - containerPort: 7077
            name: service
          - containerPort: 6066
            name: rest
          - containerPort: 8080
            name: clusterui
          - containerPort: 4040
            name: appui
          volumeMounts:
          - name: data
            mountPath: /spark_data/data
          - name: log
            mountPath: /spark_data/log
        volumes:
        - name: data
          emptyDir: {}
        - name: log
          emptyDir: {}
- kind: ReplicationController
  apiVersion: v1
  metadata: 
    name: spark-worker-rc
    labels: 
      name: spark-worker-rc
  spec: 
    replicas: 3
    selector: 
      name: spark-worker-pod
    template: 
      metadata: 
        labels: 
          name: spark-worker-pod
          uses: spark-master-svc
      spec: 
        containers: 
        - name: spark-worker
          image: quay.io/draft/k8s-spark:v0.1
          resources:
            limits: 
              cpu: 2
              memory: 8Gi
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
          - containerPort: 8080
            name: clusterui
          - containerPort: 4040
            name: appui
        volumeMounts:
        - name: work
          mountPath: /spark_data/work
        - name: data
          mountPath: /spark_data/data
        - name: log
          mountPath: /spark_data/log
        - name: checkpoint
          mountPath: /spark_data/checkpoint
      volumes:
      - name: work
        emptyDir: {}
      - name: data
        emptyDir: {}
      - name: log
        emptyDir: {}
      - name: checkpoint
        emptyDir: {}
#      - name: checkpoint
#        nfs:
#          server: nfs-server.default.kube.local
#          path: "/spark"